<!--{Navegacion Buttons}-->
<div class="item active">
	<div class="row-fluid">
		<div class="span6">
			<div class="row-fluid">
				<div class="span12">
					<div class="moduloApp" id="divInfoPeriodo">
						<div class="divTituloModulo">
							<h1>
								<a data-toggle="collapse" href="#collapseInfoPeriodo"
									class="linkCollapse">Informaci&oacute;n del periodo <i
									class="icon-chevron-down"></i>
								</a>
							</h1>
						</div>
						<div class="divContenidoModulo" id="collapseInfoPeriodo">
							<!--{Informacion del periodo}-->
						</div>
					</div>
				</div>
			</div>
			<div class="row-fluid">
				<div class="span12">
					<div class="divFormularios moduloApp" id="divEditarPeriodo">
						<form id="formEditarPeriodo" enctype="multipart/form-data"
							method="post"
							action="<!--{Root Site}-->/modules/Periodo/ControladorPeriodo.php">

							<div class="divTituloModulo">
								<h1>
									<a data-toggle="collapse" href="#collapseEditarPeriodo"
										class="linkCollapse">Editar periodo <i
										class="icon-chevron-down"></i>
									</a>
								</h1>
								<p></p>
							</div>
							<div class="divInputsFormularios collapse"
								id="collapseEditarPeriodo">
								<!--{Editar Periodo}-->

								<div class="divButtonSubmitCenter">
									<input class="btn btn-primary" type="submit" name="action"
										value="Editar Periodo" />
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
			<div class="row-fluid">
				<div class="span12">
					<div class="moduloApp" id="divCalcularPromedioPeriodo">
						<!--{Promedio}-->

						<div class="divTituloModulo">
							<h1>
								<a data-toggle="collapse" href="#collapsePromedio"
									class="linkCollapse">Calcular promedio <i
									class="icon-chevron-down"></i>
								</a>
							</h1>
						</div>
						<div class="divContenidoModulo collapse" id="collapsePromedio">
							<table class="tablaInformacion" style="text-align: center">
								<tbody>
									<tr>
										<td><a class="btn"
											onclick="calcularPromedioPeriodo(<!--{Id Periodo}-->);">
												Calcular Promedio </a></td>
										<td><div id="divPromedioPeriodo"></div>
										</td>
									</tr>
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="span6">
			<div class="row-fluid">
				<div class="span12">
					<div class="moduloApp" id="divListaAsignaturas">
						<div class="divTituloModulo">
							<h1>
								<a data-toggle="collapse" href="#collapseLista"
									class="linkCollapse">Lista de asignaturas <i
									class="icon-chevron-down"></i>
								</a>
							</h1>
						</div>
						<div class="divContenidoModulo" id="collapseLista">
							<!--{Lista de asignaturas}-->
						</div>
					</div>
				</div>
			</div>
			<div class="row-fluid">
				<div class="span12">
					<div class="divFormularios moduloApp" id="divCrearAsignatura">
						<form id="formCrearAsignatura" enctype="multipart/form-data"
							method="post"
							action="<!--{Root Site}-->/modules/Periodo/ControladorPeriodo.php">
							<div class="divTituloModulo">
								<h1>
									<a data-toggle="collapse" href="#collapseCrearAsignatura"
										class="linkCollapse">Crear asignatura <i
										class="icon-chevron-down"></i>
									</a>
								</h1>
								<p></p>
							</div>
							<div class="divInputsFormularios collapse"
								id="collapseCrearAsignatura">
								<label>Nombre</label>
								<div>
									<input name="nombre" type="text" maxlength="30" required />
								</div>

								<input type='hidden' name='id' value='<!--{Id Periodo}-->' />
								<div class="divButtonSubmitCenter">
									<input class="btn btn-primary" type="submit" name="action"
										value="Crear Asignatura" />
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
