<div class="row-fluid">
	<div id="header" class="span12">
		<div class="row-fluid">
			<div class="span5">
				<a href="http://qualify.hol.es/"><span id="logo-header" class="sprite"></span>
				</a>
			</div>
			<div class="span5"></div>
			<div class="span2"></div>
		</div>
	</div>
</div>

<!-- Nav excepciones -->
<div class="row-fluid">
	<div id="nav-excepciones-buttons" class="span12">
		<div class="row-fluid">
			<div class="span2" id="divNavButtons"></div>
			<div class="span10" id="divNavMensajes"></div>
		</div>
	</div>
</div>

