<div class="row-fluid">
	<div id="header" class="span12">
		<div class="row-fluid">
			<div class="span5">
				<a href="http://ProjectPHP/"><span id="logo-header" class="sprite"></span>
				</a>
			</div>
			<div class="span5" id="divButtonsHeader">
				<a href="http://ProjectPHP/home"> <span id="button-home"
					class="sprite"></span>
				</a> <a href="http://ProjectPHP/perfil"> <span id="button-perfil"
					class="sprite"></span>
				</a> <a href="#"> <span id="button-alertas" class="sprite"></span>
				</a>
			</div>
			<div class="span2">
				<form id="formSalir" enctype="multipart/form-data" method="post"
					action="modules/Header/ControladorHeader.php">
					<input id="botonSalir" type="submit" value="" /> <input
						type="hidden" name="action" value="Cerrar Sesion">
				</form>
			</div>
		</div>
	</div>
</div>

<div class="row-fluid" id="divNombreProfile">
	<div><!--{Link Usuario}--></div>
</div>

<!-- Nav excepciones -->
<div class="row-fluid">
	<div id="nav-excepciones-buttons" class="span12">
		<div class="row-fluid">
			<div class="span2" id="divNavButtons"></div>
			<div class="span10" id="divNavMensajes"></div>
		</div>
	</div>
</div>
