<div class="row-fluid">
	<div id="header" class="span12">
		<div class="row-fluid">
			<div class="span4">
				<a href="/"><span id="logo-header"
					class="sprite"></span> </a>
			</div>
			<div class="span8" id="divButtonsHeader">
				<a href="<!--{Root Site}-->"> <span id="button-home"
					class="sprite"></span>
				</a>
				<!-- <a href="http://qualify.hol.es/perfil"> <span id="button-perfil"
					class="sprite"></span>
				</a> <a href="#"> <span id="button-alertas" class="sprite"></span>
				</a> -->
				<a onclick="cerrarSesion();" href="#"> <span id="button-salir"
					class="sprite"></span>
				</a>
				<form id="formCerrarSesion" name="formCerrarSesion"
					enctype="multipart/form-data" method="post"
					action="<!--{Root Site}-->/modules/header/ControladorHeader.php">
					<input type="hidden" name="action" value="Cerrar Sesion" />
				</form>
			</div>
		</div>
	</div>
</div>

<div class="row-fluid" id="navHeaderProfile">
	<!--{Link Usuario}-->
</div>

<!-- Nav excepciones -->
<div class="row-fluid">
	<div id="nav-excepciones-buttons" class="span12">
		<div class="row-fluid">
			<div class="span2" id="divNavButtons"></div>
			<div class="span10" id="divNavMensajes"></div>
		</div>
	</div>
</div>
