<div class="span6">
	<div class="row-fluid">
		<div class="span12">
			<div class="divFormularios moduloApp">
				<form id="formRegistro" enctype="multipart/form-data" method="post"
					action="modules/Home/ControladorHome.php">
					<div class="descripcionFormularios">
						<h2>Registro</h2>
						<p>Registrese aqu&iacute; gratis</p>
					</div>
					<div class="divInputsFormularios">
						<label>Nombre </label>
						<div>
							<input name="nombre" type="text" maxlength="20" required />
						</div>
						<label>Email </label>
						<div>
							<input onblur="comprobarEmailDisponible();" name="email"
								id="emailRegistro" type="email" required maxlength="50" />
							<div id="divEmailDisponible"></div>
						</div>
						<label>Nick </label>
						<div>
							<input onblur="comprobarNickDisponible();" id="nickRegistro"
								name="nick" type="text" maxlength="15" required />
							<div id="divNickDisponible"></div>
						</div>
						<label>Password </label>
						<div>
							<input name="password" type="password" maxlength="10" required />
						</div>
						<label>Foto </label>
						<div>
							<input name="foto" type="file" />
						</div>

						<input class="btn btn-primary" id="submitRegistro" type="submit"
							name="action" value="Registrar" />
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

<div class="span6">
	<div class="row-fluid">
		<div class="span12">
			<div class="divFormularios moduloApp">
				<div class="descripcionFormularios">
					<h2>Login</h2>
					<p>Inicie sesi&oacute;n</p>
				</div>
				<form id="formLogin" enctype="multipart/form-data" method="post"
					class="well form-inline" action="modules/Home/ControladorHome.php">
					<div class="divInputsFormularios" id="divFormLogin">
						<input type="text" class="input-small" placeholder="Email"
							maxlength="50" name="email" /> <input type="password"
							class="input-small" placeholder="Password" name="password"
							maxlength="10" /> <input class="btn btn-primary" type="submit"
							name="action" value="Login" />
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
